### ISSUE TITLE
异步调用的方式很奇怪

### ISSUE THREAD

**Issue by dempeZheng** [i1see1you/QiuRPC#2]
将异步消息放到了ThreadLocal中，同时又 new RpcResponse()返回

``` java
    //如果是异步，则封装context
            RpcContext.getContext().setFuture(new FutureAdapter<Object>(invokeFuture));
            return new RpcResponse();

```

**Comment by i1see1you** [comment]
这个是为了防止异步调用时，客户端还用同步方式获取result，直接返回new的空对象的话，即使异步调用时客户端同步方式获取结果也不会报错，只是获取到的结果为空对象而已。

**Comment by dempeZheng** [comment]
之前看过的几个rpc都是类似的做法：
异步返回一个responseFuture或者 callback，
同步方式 ：在这个responseFuture上封装，responseFuture.getValue(int timeout)

**Comment by i1see1you** [comment]
这样同步和异步是采用了不同的接口吧？这个项目为了保持简洁，同步和异步都是一个接口
